### ISSUE TITLE
download_codebook throws an error message

### ISSUE THREAD

**Issue by jobreu** [expersso/gesis#11]
First of all, I wanted to thank you for creating this great package!
I am planning on using it in a workshop I will teach and noticed that download_codebook gives the error message "Error in is.url(url) : length(url) == 1 is not TRUE"
Could it be that this is because the particular study whose codebook I wanted to download has multiple files whose names include "_cdb"?
If you want to reproduce the error, the study number is "4587".

**Comment by expersso** [comment]
Thanks! Hadn't come across a case with multiple files. Should be fixed now.

**Comment by jobreu** [comment]
Thx for the quick fix! If I understand the function correctly, download_codebook now downloads the first file whose name includes '_cdb'. This works fine for the cumulated ALLBUS dataset (ZA4587). However, it does not work for other datasets that have multiple codebooks. E.g., the 2008 integrated EVS dataset (ZA4800) has codebooks for every country, and the combined variable report/codebook (ZA4800_cdb.pdf) is the last one in the list.
In my own script, I have now solved this by creating a custom function based on your download_codebook function:
get_codebook <- function (doi, path = ".", quiet = FALSE) 
{
  for (d in doi) {
    url <- paste0("https://dbk.gesis.org/dbksearch/SDesc2.asp?db=E&no=", 
                  d)
    nodename <- paste0("ZA", d, "_cdb.pdf")
    page <- read_html(url)
    node <- html_nodes(page, xpath = "//a[contains(text(), '_cdb')]")
    node <- subset(node, html_text(node) == nodename)
    node <- paste0("https://dbk.gesis.org/dbksearch/", html_attr(node, 
                                                                 "href"))
    resp <- GET(node)
    if (!quiet) 
      message("Downloading codebook for DOI: ", d)
    filename <- gsub("^.*?\"|\"", "", resp$headers$`content-disposition`)
    filename <- file.path(path, filename)
    writeBin(content(resp, "raw"), filename)
  }
} 

In essence, I just added a subset command to select the filename that matches doi_cdb.pdf from the nodelist. This might not be the most elegant solution but it works.
By the same logic, you can also easily create a download_questionnaire function (by simply replacing
nodename <- paste0("ZA", d, "_cdb.pdf") with nodename <- paste0("ZA", d, "_q.pdf") and node <- html_nodes(page, xpath = "//a[contains(text(), '_cdb')]") with node <- html_nodes(page, xpath = "//a[contains(text(), '_q')]"); and maybe also replacing the word "codebook" in the message with "questionnaire".

**Comment by expersso** [comment]
Thanks, this is very useful. If you're familiar with pull requests and the `testthat` package, it'd be great if you could implement this, add some tests for it, and send me a PR. If not, I will take a look at this at my earliest convenience.
