### ISSUE TITLE
argument name doi can be misleading

### ISSUE THREAD

**Issue by jobreu** [expersso/gesis#12]
download_codebook and download_dataset both have an argument called doi and the description of that argument is "The unique identifier(s) for the data set(s)". This may be misleading/confusing for users as the number that is needed here is the study number (i.e., the number that comes after "ZA" in the dataset title in the DBK). For example, the DOI for ZA4587 is 10.4232/1.13048 (as specified in the bibliographic citation for that dataset), but the "doi" required by the gesis package functions is "4587". Hence, to avoid potential confusion it might help to change the name and description of the argument. One suggestion that I can think of could be argument doi = study (or studynr) + Description = "Study number(s) for the data set(s). The number that comes after "ZA" in the DBK study title".
For consistency, this would also require changing the column name created by the get_datasets function from doi to study or studynr or whatever else is used as an argument for download_codebook and download_dataset.

**Comment by expersso** [comment]
Thanks a lot. This is a subtle point that I didn't consider, but I agree with your description.

If you're familiar with pull requests and the `testthat` package, it'd be great if you could implement this, add some tests for it and send me a PR. If not, I will take a look at this at my earliest convenience.

**Comment by briatte** [comment]
I personally rename the `doi` column produced by `gesis` to `gesis_id` to avoid that confusion.

**Comment by jobreu** [comment]
@briatte I do the same :-)

**Comment by expersso** [comment]
This was clearly a design-mistake on my part when I first wrote this. The question now is: does it make sense to change this, and risk breaking people's code, or should we just leave it as is?

Interested in hearing your views (also @fsolt).

**Comment by briatte** [comment]
Hi @jobreu and @expersso,

I believe that PR https://github.com/expersso/gesis/pull/16 starts fixing the issue discussed above, as well as the one I reported in #15.
