### ISSUE TITLE
download_codebook fails for files without "_cdb"

### ISSUE THREAD

**Issue by vladgross** [expersso/gesis#8]
Thanks for writing this package, it's very useful!

I have noticed that not all dois have a codebook section. So, there's an error when the `download_codebook()` function does not find one on the Gesis website. For example `download_codebook(doi = c("5876", "5913", "5689"))` evaluates the first doi and then stops because doi `"5913" `does not have a codebook on the Gesis website (although `"5689"` does and should be downloaded).

However, it would be great to have some documentation/codebook for the corresponding data. One solution would be to download the questionnaire for those cases and display a warning that a questionnaire was downloaded instead of a codebook. Another would be to find/construct a codebook from another online source (like ICPSR).

**Comment by expersso** [comment]
This appears fixed, possibly by ff943a3a4244b95d76b966245e06c53504613276, or by a change on the website. 

If it fails for other codebooks, I recommend some standard error handling, e.g. 

```
purrr::walk(c("asdfasdf5876", "5913", "5689"), purrr::safely(download_codebook))
```

Automatically downloading something other than the codebook in the absence of such doesn't seem like a great idea to me. As an alternative, one could implement e.g. `download_questionnaire` and conditionally call that whenever `download_codebook` fails.
